remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Marcos Ramírez
description: El tiempo es tu herramienta de aprendizaje
show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
